<a href="https://colab.research.google.com/github/Shreyash-0699/Pytorch-learning/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


## Tensors
- A torch.tensor is a multi-dimensional matrix containing elements of a single data type.
- Similar to Numpy arrays, but full of fun things that make them work bettter on GPU's (vs regular CPU's)
- default data type of float32
- more suitable for deep learning than a numpy array

In [ ]:
import torch
import numpy as np

In [ ]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [ ]:
np_random = np.random.rand(3,4)
np_random

array([[0.62366976, 0.84708817, 0.34300265, 0.83587965],
       [0.76952773, 0.06274248, 0.38599088, 0.33377729],
       [0.7597618 , 0.66382005, 0.82249177, 0.01547807]])

In [ ]:
tensor_2dim = torch.randn(3,4)
tensor_2dim

tensor([[ 0.1534,  0.5980, -1.5959, -0.8703],
        [ 0.8892,  0.0371, -0.2931,  0.0114],
        [ 0.0791, -0.8634,  1.0060,  1.2308]])

In [ ]:
tensor_3dim = torch.zeros(2,3,4)
tensor_3dim

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
### Create tensor out of numpy array
my_tensor = torch.tensor(np_random)
my_tensor

tensor([[0.6237, 0.8471, 0.3430, 0.8359],
        [0.7695, 0.0627, 0.3860, 0.3338],
        [0.7598, 0.6638, 0.8225, 0.0155]], dtype=torch.float64)

In [ ]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
# Reshape if we don't know the number of items using -1
my_torch_new = torch.arange(10)
my_torch_new

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch_new.reshape(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch_n = torch.arange(10)
my_torch_n

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch_view = my_torch_n.view(2,5)
my_torch_view

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
# reshape and view, both will update the underlying data
# with reshape --> in some cases it may make a copy of the tensor
# with view --> it always returns the reference to the same tensor

In [ ]:
my_torch_sample = torch.arange(10)
my_torch_sample

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch_reshape = my_torch_sample.reshape(2,5)
torch_reshape

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch_sample[1] = 42069
my_torch_sample

tensor([    0, 42069,     2,     3,     4,     5,     6,     7,     8,     9])

In [ ]:
torch_reshape

tensor([[    0, 42069,     2,     3,     4],
        [    5,     6,     7,     8,     9]])

In [ ]:
# Slices
my_torch_try = torch.arange(10)
my_torch_try

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Grab a specific item
my_torch_try[7]

tensor(7)

In [ ]:
# Grab slice
my_torch_re = my_torch_try.reshape(5,2)
my_torch_re

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [ ]:
my_torch_re[:,1]

tensor([1, 3, 5, 7, 9])

#### Tensor Math Operations
- Add, Subtract, Multiply, Divide, Remainders, Exponents
- Shorthand and uh, Longhand
- Reassignment

In [ ]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [ ]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [ ]:
# Addition Longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [ ]:
# Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [ ]:
# Sub Function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [ ]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [ ]:
# Mul longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [ ]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [ ]:
# Div Longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [ ]:
# Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [ ]:
# Remainder longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [ ]:
# Exponents / power
tensor_a ** tensor_b

tensor([    1,    64,  2187, 65536])

In [ ]:
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [ ]:
# Another way to write longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [ ]:
# Reassignment
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [ ]:
# tensor_a = tensor_a + tensor_b
# or
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [ ]:
tensor_a

tensor([ 6,  8, 10, 12])